/*
 * org_xunyss_htmlsnap4j_HtmlsnapJni.h
 *
 * created on 2013.09.30
 * author : XUNY
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xunyss_htmlsnap4j_HtmlsnapJni */

#ifndef _Included_org_xunyss_htmlsnap4j_HtmlsnapJni
#define _Included_org_xunyss_htmlsnap4j_HtmlsnapJni
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    CreateInstance
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_CreateInstance
  (JNIEnv *, jobject);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    ReleaseInstance
 * Signature: ()Z
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_ReleaseInstance
  (JNIEnv *, jobject);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    Snap
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lorg/anzu/htmlsnap/HtmlsnapOptions;)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_Snap
  (JNIEnv *, jobject, jint, jstring, jstring, jobject);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    SnapUrl
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_SnapUrl
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    SnapHtmlString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_SnapHtmlString
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    ReSnap
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_ReSnap
  (JNIEnv *, jobject);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    EnableActiveX
 * Signature: (Z)V
 */

JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_EnableActiveX
  (JNIEnv *, jobject, jboolean);
/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    EnableJava
 * Signature: (Z)V
 */

JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_EnableJava
  (JNIEnv *, jobject, jboolean);
/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    EnableScript
 * Signature: (Z)V
 */

JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_EnableScript
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    SetRenderEngine
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_SetRenderEngine
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    SetCode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_SetCode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    SetTimeOut
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_SetTimeOut
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    SetDelayTime
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_SetDelayTime
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    SetForceSnap
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_SetForceSnap
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    SetSnapDimension
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_SetSnapDimension
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    SetClipRect
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_SetClipRect
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    SetZoom
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_SetZoom
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    SetDPI
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_SetDPI
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    SetJPEGQuality
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_SetJPEGQuality
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    SetDither
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_SetDither
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    SetTIFFEncoder
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_SetTIFFEncoder
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    SetSmoothingMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_SetSmoothingMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    SetInterpolationMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_SetInterpolationMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    SetProxy
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_SetProxy
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    SetAsync
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_SetAsync
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    SetLogonUser
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_SetLogonUser
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    SetAuthUserAndPasswd
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_SetAuthUserAndPasswd
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    SetPostData
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_SetPostData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    SetCookie
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_SetCookie
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    SetThreshold
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_SetThreshold
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    DrawText
 * Signature: (IILjava/lang/String;IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_DrawText
  (JNIEnv *, jobject, jint, jint, jstring, jint, jint, jstring);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    saveImage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_saveImage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    saveMultipageTiff
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_saveMultipageTiff
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    GetLinks
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_GetLinks
  (JNIEnv *, jobject);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    GetFrames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_GetFrames
  (JNIEnv *, jobject);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    GetTitle
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_GetTitle
  (JNIEnv *, jobject);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    GetSource
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_GetSource
  (JNIEnv *, jobject);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    GetText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_GetText
  (JNIEnv *, jobject);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    GetImageWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_GetImageWidth
  (JNIEnv *, jobject);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    GetImageHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_GetImageHeight
  (JNIEnv *, jobject);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    GetCookie
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_GetCookie
  (JNIEnv *, jobject);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    GetCookie2
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_GetCookie2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    GetBufferedImage
 * Signature: ()Ljava/awt/image/BufferedImage;
 */
JNIEXPORT jobject JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_GetBufferedImage
  (JNIEnv *, jobject);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    GetThumbBufferedImage
 * Signature: (III)Ljava/awt/image/BufferedImage;
 */
JNIEXPORT jobject JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_GetThumbBufferedImage
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    GetImageBytes
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_GetImageBytes
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    GetThumbImageBytes
 * Signature: (Ljava/lang/String;III)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_GetThumbImageBytes
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    GetErrorCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_GetErrorCode
  (JNIEnv *, jobject);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    Clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_Clear
  (JNIEnv *, jobject);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    IsGoodUrlForSnap
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_IsGoodUrlForSnap
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    MakeThumbnailImage
 * Signature: (Ljava/lang/String;Ljava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_MakeThumbnailImage
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    MakeGrayImage
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_MakeGrayImage
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     org_xunyss_htmlsnap4j_HtmlsnapJni
 * Method:    ReduceColor
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_xunyss_htmlsnap4j_HtmlsnapJni_ReduceColor
  (JNIEnv *, jobject, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
